repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: 'v0.7.0'
  hooks:
    - id: ruff
- repo: https://github.com/iterative/dvc
  rev: 3.55.2
  hooks:
  - id: dvc-pre-commit
    additional_dependencies:
    - .[all]
    language_version: python3
    stages:
    - pre-commit
  - id: dvc-pre-push
    additional_dependencies:
    - .[all]
    language_version: python3
    stages:
    - pre-push
  - id: dvc-post-checkout
    additional_dependencies:
    - .[all]
    language_version: python3
    stages:
    - post-checkout
    always_run: true
